---
- hosts: all
  become: yes
  user: vagrant
  tasks:
  - name: Install net-tools
    yum: name=net-tools state=installed

  - name: Add a yum repository
    yum_repository:
      name: docker
      description: Docker Repository
      baseurl: https://yum.dockerproject.org/repo/main/centos/7/
      enabled: 1
      gpgcheck: 1
      gpgkey: https://yum.dockerproject.org/gpg
    become: yes

  - name: Install docker-engine
    yum: name=docker-engine state=installed
